In [1]:
import numpy as np
from control import matlab

# 演習問題
## 12.2

In [54]:
# 問題設定
A = np.array([[-1, 0],[0, 2]])
B = np.array([[3], [-1]])
C = np.array([[-2, 5]])
D = np.array([[0]])

In [55]:
A_star = A.T
B_star = C.T

- 可制御性判別

In [56]:
Uc_star = matlab.ctrb(A_star, B_star)
Rc_star = np.linalg.matrix_rank(Uc_star)

In [57]:
print("ランク:",Rc_star,"サイズ:",min(Uc_star.shape))

ランク: 2 サイズ: 2


- 可制御なのでオブザーバーが組める

In [58]:
#元の極を見てみる
np.linalg.eig(A_star)[0]

array([-1.,  2.])

In [93]:
# 配置先の極
poles = [-2, -2]

In [60]:
F_star = matlab.place(A_star, B_star, poles)

ValueError: at least one of the requested pole is repeated more than rank(B) times

- matlab.place関数ではBのランク個以上の重根を設定できないらしい…

## 12.3

In [123]:
# 問題設定
A = np.array([[0, 0, 0],[1, 0, 0], [0, 1, 0]])
B = np.array([[3], [0], [0]])
C = np.array([[0, 0, 2]])
D = np.array([[0]])

In [124]:
A_star = A.T
B_star = C.T

- 可制御性判別

In [125]:
Uc_star = matlab.ctrb(A_star, B_star)
Rc_star = np.linalg.matrix_rank(Uc_star)

In [126]:
print("ランク:",Rc_star,"サイズ:",min(Uc_star.shape))

ランク: 3 サイズ: 3


- 極配置法で極を移動

In [127]:
#元の極を見てみる
np.linalg.eig(A_star)[0]

array([0., 0., 0.])

In [128]:
# 配置先の極
poles = [-3, -2+2j, -2-2j]

In [129]:
F_star = matlab.place(A_star, B_star, poles)

In [130]:
L = F_star.T
L

matrix([[12. ],
        [10. ],
        [ 3.5]])

In [131]:
np.linalg.eig(A-np.dot(L, C))[0]

array([-2.+2.j, -2.-2.j, -3.+0.j])

- 重根でもイケる方法を探してみるが…
    - https://ossyaritoori.hatenablog.com/entry/2018/05/16/%E6%A5%B5%E9%85%8D%E7%BD%AE%E3%81%AE%E5%AE%9F%E8%A3%85%EF%BC%9A%E3%82%A2%E3%83%83%E3%82%AB%E3%83%BC%E3%83%9E%E3%83%B3%E6%B3%95%E3%81%AEMATLAB%E5%AE%9F%E8%A3%85

In [133]:
def es(A, B, poles):

    U_1, S_1, V_1 = np.linalg.svd(np.block([poles[0]*np.eye(2)-A, B]))
    U_2, S_2, V_2 = np.linalg.svd(np.block([poles[1]*np.eye(2)-A, B]))

    size = len(S_1)
    VV = np.block([V_1[:,size:3], V_2[:,size:3]])
    print(VV)
    
    return VV[size-1:2,:]/VV[0:1,:]

In [134]:
a = es(A_star, B_star, poles)
a

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 